In [3]:
import pandas as pd

In [5]:
df=pd.read_csv("train.csv.zip")

In [6]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [9]:
df.describe()

id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [10]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [20]:
df.shape

(20800, 5)

In [21]:
df=df.dropna()

In [22]:
df.shape

(18285, 5)

In [23]:
X=df.drop('label',axis=1)

In [24]:
y=df["label"]

In [32]:
import tensorflow as tf

In [ ]:
pip install tensorflow

In [33]:
tf.__version__

'2.13.0'

In [34]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [35]:
### Vocabulary size
voc_size=5000

In [36]:
messages=X.copy()

In [37]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [38]:
messages.reset_index(inplace=True)

In [41]:
import nltk
import re
from nltk.corpus import stopwords


In [ ]:
pip install nltk

In [42]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


In [44]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[53, 2358, 1357, 3594, 459, 1069, 3451, 2441, 1822, 3060],
 [4473, 920, 306, 4009, 1264, 4229, 1364],
 [2546, 3615, 3143, 3505],
 [4687, 3424, 189, 3857, 4953, 2161],
 [4344, 1264, 1301, 3890, 782, 4797, 1264, 3270, 2213, 4912],
 [3791,
  223,
  340,
  1528,
  4313,
  1204,
  2065,
  2151,
  823,
  2080,
  4934,
  3397,
  1463,
  224,
  1364],
 [389, 4078, 742, 14, 4677, 3480, 1365, 1017, 924, 4478, 4062],
 [4579, 4730, 2176, 4415, 3286, 2373, 1204, 2011, 924, 4478, 4062],
 [1798, 4884, 2183, 3754, 3661, 2557, 1898, 2829, 1204, 4390],
 [1630, 2003, 782, 4654, 1461, 181, 1242, 3228],
 [3492, 3956, 4293, 3683, 1119, 1668, 3347, 4320, 1464, 3588, 4557],
 [3857, 69, 459, 2557, 1204, 3286],
 [486, 3581, 476, 2599, 1925, 1989, 1416, 4503, 2440],
 [1586, 1013, 4633, 937, 16, 3800, 2411, 924, 4478, 4062],
 [2414, 458, 1934, 3800, 2934, 924, 4478, 4062],
 [1625, 4405, 1752, 1685, 1516, 3763, 1598, 3622, 3086, 1798],
 [169, 4279, 920],
 [3445, 1496, 4244, 2694, 1204, 1156, 4314, 1364],
 [299, 1

In [45]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2441 1822 3060]
 [   0    0    0 ... 1264 4229 1364]
 [   0    0    0 ... 3615 3143 3505]
 ...
 [   0    0    0 ...  924 4478 4062]
 [   0    0    0 ... 4482 3571 4058]
 [   0    0    0 ... 1003 4324  812]]


In [46]:
embedded_docs[0]


array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   53,
       2358, 1357, 3594,  459, 1069, 3451, 2441, 1822, 3060])

In [47]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [48]:
len(embedded_docs),y.shape


(18285, (18285,))

In [49]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)


In [50]:
X_final.shape,y_final.shape


((18285, 20), (18285,))

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)


In [52]:
pip install scikit-learn

     ---------------------------------------- 9.2/9.2 MB 1.9 MB/s eta 0:00:00
  Using cached scipy-1.10.1-cp38-cp38-win_amd64.whl (42.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [54]:

### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 18s 54ms/step - loss: 0.3568 - accuracy: 0.8309 - val_loss: 0.2082 - val_accuracy: 0.9099
Epoch 2/10
192/192 [==============================] - 9s 47ms/step - loss: 0.1441 - accuracy: 0.9416 - val_loss: 0.2043 - val_accuracy: 0.9180
Epoch 3/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0969 - accuracy: 0.9643 - val_loss: 0.2262 - val_accuracy: 0.9125
Epoch 4/10
192/192 [==============================] - 8s 43ms/step - loss: 0.0641 - accuracy: 0.9793 - val_loss: 0.2827 - val_accuracy: 0.9152
Epoch 5/10
192/192 [==============================] - 8s 42ms/step - loss: 0.0419 - accuracy: 0.9862 - val_loss: 0.2947 - val_accuracy: 0.9112
Epoch 6/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0265 - accuracy: 0.9916 - val_loss: 0.3569 - val_accuracy: 0.9148
Epoch 7/10
192/192 [==============================] - 9s 44ms/step - loss: 0.0172 - accuracy: 0.9946 - val_loss: 0.3862 - val_accuracy: 0.911

In [55]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [58]:
y_pred=model.predict(X_test)


189/189 [==============================] - 2s 7ms/step
